server:
  port: 10086

spring:
  application:
    name: itcast-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka
  server:
    eviction-interval-timer-in-ms: 5000 #剔除无效连接的时间间隔
    enable-self-preservation: false #关闭自我保护状态




