server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hm49?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hwy
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

mybatis:
  type-aliases-package: com.leyou.item.pojo